### PR TITLE
Print a warning about SecurityManager being deprecated

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by bmarwell** [comment]
This PR has too much noise on unrelated lines. I cannot even see the actual change.

**Comment by bmarwell** [comment]
What about https://github.com/groovy/GMavenPlus/pull/287 ?

**Comment by keeganwitt** [comment]
> What about #287 ?

Oops. Thank you for the reminder. I'm doing a bad job balancing this with my personal life right now and lost track of this. That would be the better solution. We probably should move forward with that one and not this one.

**Comment by keeganwitt** [comment]
Moved the unrelated changes into a separate PR: #290.

**Pull request closed without merging**
